# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "kiki_gem"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Josh Rubinstein"]
  s.date = "2012-11-16"
  s.description = "TODO: longer description of your gem"
  s.email = "josh@estately.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "kiki_gem.gemspec",
    "kiki_gem/.document",
    "kiki_gem/.gitignore",
    "kiki_gem/.rspec",
    "kiki_gem/.travis.yml",
    "kiki_gem/Gemfile",
    "kiki_gem/Gemfile.lock",
    "kiki_gem/LICENSE.txt",
    "kiki_gem/README.rdoc",
    "kiki_gem/Rakefile",
    "kiki_gem/VERSION",
    "kiki_gem/kiki_gem.gemspec",
    "kiki_gem/lib/kiki_gem.rb",
    "kiki_gem/spec/kiki_gem_spec.rb",
    "kiki_gem/spec/spec_helper.rb",
    "lib/kiki_gem.rb",
    "spec/kiki_gem_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/hungrysquirrel/kiki_gem"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "TODO: one-line summary of your gem"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
  end
end

